services:
  - type: worker
    name: panda-mans-world-vibes
    runtime: python
    buildCommand: bash build.sh
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SOUNDCLOUD_CLIENT_ID
        sync: false
